my_string = input('Красная или синяя: ')
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print('Красная или синяя'.replace(' ', ''))
print(my_string[0])
print(my_string[-1])
